pipeline {
    agent any

    environment {
        DISABLE_AUTH = 'true'
        DB_ENGINE    = 'sqlite'
    }

    stages {
        stage('Setup') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps"
                    ls –lah
                '''
                sh 'ls -all'
                nodejs(nodeJSInstallationName: 'NodeJS 10.x') {
                    sh 'npm --version'
                    sh 'npm config ls'
                }
                sh 'npm --version'
                sh 'npm config ls'
            }
        }

        stage('Build') {
            steps {
                echo 'Building'

                timeout(time: 3, unit: 'MINUTES') {
                    retry(3) {
                        sh 'echo "Hello World"'
                    }
                }

                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Testing'
                sh 'printenv'
            }
        }

        stage('Deploy') {
            when {
                branch 'master'
            }
            steps {
                echo 'Deploying'
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }

        success {
            echo 'This will run only if successful'
            archiveArtifacts artifacts: '*.MD', fingerprint: true, caseSensitive: false
        }

        failure {
            echo 'This will run only if failed'
        }

        unstable {
            echo 'This will run only if the run was marked as unstable'
        }

        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
