pipeline {
    agent any

    environment {
        DISABLE_AUTH = 'true'
        DB_ENGINE    = 'sqlite'
    }

    stages {
        stage('Setup') {
            steps {
                sh 'ls -a'
            }
        }

        stage('Build') {
            steps {
                timeout(time: 3, unit: 'MINUTES') {
                    retry(3) {
                        sh 'echo "Hello World"'
                    }
                }

                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }

        stage('Test') {
            steps {
                sh 'printenv'
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }

        success {
            echo 'This will run only if successful'
            archiveArtifacts artifacts: '*.MD', fingerprint: true, caseSensitive: false
        }

        failure {
            echo 'This will run only if failed'
        }

        unstable {
            echo 'This will run only if the run was marked as unstable'
        }

        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}